# Generated by Django 4.2.7 on 2024-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='posts.post'),
        ),
    ]
